<?php


return [
    'super_admin' => [
        'author' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'brand' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'category' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'country' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'faq' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'founder' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'genre' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'payment' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'product' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'productrelaise' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'role' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'status' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'tarife' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'user' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
            'roles',
            'sendEmailVerification',
            'checkEmailVerification',
        ],
    ],
    'moderator' => [
        'author' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'brand' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'category' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'faq' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'founder' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'genre' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'product' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'productrelaise' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'tarife' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'user' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
            'roles',
            'sendEmailVerification',
            'checkEmailVerification',
        ],
    ],
    'editor' => [
        'author' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'brand' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'category' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'faq' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'founder' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'genre' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'product' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'productrelaise' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
        'user' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
            'roles',
            'sendEmailVerification',
            'checkEmailVerification',
        ],
        'tarife' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
        ],
    ],
    'user' => [
        'user' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
            'roles',
            'sendEmailVerification',
            'checkEmailVerification',
        ],
    ],
    'superuser' => [
        'user' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
            'roles',
            'sendEmailVerification',
            'checkEmailVerification',
        ],
    ],
    'newuser' => [
        'user' => [
            'index',
            'store',
            'show',
            'update',
            'destroy',
            'roles',
            'sendEmailVerification',
            'checkEmailVerification',
        ],
    ],
];